backend:
  name: git-gateway
  branch: master

media_folder: "src/img/uploads" # Media files will be stored in the repo under src/img/uploads
public_folder: "img/uploads"  # The src attribute for uploaded media will begin with img/uploads

collections:
  - name: "apie-mus" # Used in routes, e.g., /admin/collections/blog
    label: "Apie mus" # Used in the UI
    folder: "src/apie-mus" # The path to the folder where the documents are stored
    create: false # Allow users to create new documents in this collection. Values true/false
    fields: # The fields for each document, usually in front matter
      - {label: "default string field", name: "title", widget: "string"}
      - {label: "default image field", name: "photo", widget: "image"}
      - {label: "default layout file", name: "layout", widget: "hidden", default: "apie-mus.pug"} # pug file in layouts dir
      - {label: "default hidden field", name: "hidden_field", widget: "hidden", default: "paslÄ—ptas-default"}
      - {label: "default content field", name: "body", widget: "markdown"}
